version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-west-1 | docker login --username AWS --password-stdin 751253673357.dkr.ecr.us-west-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t trainingapp .
      - docker tag trainingapp:latest 751253673357.dkr.ecr.us-west-1.amazonaws.com/trainingapp:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 751253673357.dkr.ecr.us-west-1.amazonaws.com/trainingapp:latest
